[package]
name = "tagfs"
version = "0.1.0"
authors = ["Ilmari Autio <ilmari.autio@gmail.com>"]

[dependencies]
hyper = "0.11.8"
futures = "0.1.17"
tokio-core = "0.1.10"
serde = "1.0.23"
serde_json = "1.0.8"
serde_derive = "1.0.23"